apiVersion: v1
kind: Secret
metadata:
  name: fashion-club-secrets
  namespace: fashion-club
type: Opaque
stringData:
  # Practice Dummy Credentials for AWS EKS & Local Testing
  ADMIN_EMAIL: "hanamanttaranal19@gmail.com"
  ADMIN_PASSWORD: "12345"
  DB_USER: "atelier_admin"
  DB_PASSWORD: "atelier_dummy_secure_pass_123"
  JWT_SECRET: "dummyJwtSecretKeyForEksPractice2026AtelierFashionClub"
  GEMINI_API_KEY: "AIStudio_Dummy_Practice_Gemini_Key_2026"
