server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: fashion-club-java-backend
  datasource:
    url: ${DB_URL:jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:atelier_fashion_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${DB_USER:atelier_admin}
    password: ${DB_PASSWORD:atelier_dummy_secure_pass_123}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  admin:
    email: hanamanttaranal19@gmail.com
    password: "12345"
  jwt:
    secret: atelierFashionClubSecureJwtSecretKey2026EksArgoCd
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
