server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: fashion-club-java-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:atelier_fashion_db}
    username: ${DB_USER:atelier_admin}
    password: ${DB_PASSWORD:atelier_secure_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  admin:
    email: hanamanttaranal19@gmail.com
    password: "12345"
  jwt:
    secret: atelierFashionClubSecureJwtSecretKey2026EksArgoCd
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
